### ISSUE TITLE
Retry request after failing

### ISSUE THREAD

**Issue by erikpeterson23** [quatrope/pycf3#3]
We implemented this code and it worked. This could be implemented into the code for the equatorial_search/other functions. My code often froze since the site was not very stable.
```
import pycf3
import time
import signal

from retry import retry
from tqdm import tqdm

cf3 = pycf3.CF3()

#Create something that can make a timer
def handler(signum, frame):
    raise TimeoutError()
    
signal.signal(signal.SIGALRM, handler)

#Implementing a retry method to try again if the timer goes off (giving an error)
@retry(tries = 10,delay = 0.5)
def eq2(cf3,**kwargs):
    signal.alarm(30)
    result = cf3.equatorial_search(**kwargs)
    signal.alarm(0)
    return result
```

**Comment by leliel12** [comment]
why is tqdm imported? (i ask mostly if some part of code is missin in the example)

**Comment by leliel12** [comment]
This is the solution needed to be implemented
https://www.peterbe.com/plog/best-practice-with-retries-with-requests

**Comment by erikpeterson23** [comment]
Dear Juan,

The tqdm is not necessary. I apologize. I only had it so I could track the progress on my for loop later.

Sincerely,

Erik Peterson

Enviado desde mi iPhone

El sep. 25, 2019, a la(s) 7:34 p. m., Juan BC <notifications@github.com<mailto:notifications@github.com>> escribió:


why is tqdm imported? (i ask mostly if some part of code is missin in the example)
